export const algo = {
  id: 1,
  algorithm_id: 1,
  name: 'ePoct',
  version: 'Local',
  description: 'loremp ipsum',
  author: 'Domatchief',
  created_at: '2019-06-11T17:08:08.232+02:00',
  updated_at: '2019-06-11T17:08:08.232+02:00',
  diagnostics: {
    '4': {
      id: 4,
      reference: 'DD7',
      label: 'Severe LRTI',
      differential: { top_conditions: [], conditions: [] },
      nodes: {
        '7': {
          top_conditions: [],
          conditions: [],
          id: 7,
          children: [9, 10, 11, 12],
        },
        '9': {
          top_conditions: [
            {
              first_id: 15,
              first_type: 'Answer',
              first_node_id: 7,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 9,
          children: [6],
        },
        '10': {
          top_conditions: [
            {
              first_id: 15,
              first_type: 'Answer',
              first_node_id: 7,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 10,
          children: [6],
        },
        '11': {
          top_conditions: [
            {
              first_id: 15,
              first_type: 'Answer',
              first_node_id: 7,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 11,
          children: [6],
        },
        '12': {
          top_conditions: [
            {
              first_id: 15,
              first_type: 'Answer',
              first_node_id: 7,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 12,
          children: [6],
        },
        '18': {
          top_conditions: [],
          conditions: [],
          id: 18,
          children: [16, 14, 15],
        },
      },
      diagnosis: {
        '6': {
          top_conditions: [
            {
              first_id: 25,
              first_type: 'Answer',
              first_node_id: 12,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
            {
              first_id: 22,
              first_type: 'Answer',
              first_node_id: 10,
              operator: 'and_operator',
              second_id: 23,
              second_type: 'Answer',
              second_node_id: 11,
            },
            {
              first_id: 19,
              first_type: 'Answer',
              first_node_id: 9,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          disease_id: 4,
          name: 'Severe lower respiratory tract infection',
          id: 6,
          type: 'FinalDiagnostic',
          treatments: {
            '14': {
              top_conditions: [
                {
                  first_id: 29,
                  first_type: 'Answer',
                  first_node_id: 18,
                  operator: null,
                  second_id: null,
                  second_type: null,
                  second_node_id: null,
                },
              ],
              conditions: [],
              id: 14,
            },
            '15': {
              top_conditions: [
                {
                  first_id: 30,
                  first_type: 'Answer',
                  first_node_id: 18,
                  operator: null,
                  second_id: null,
                  second_type: null,
                  second_node_id: null,
                },
              ],
              conditions: [],
              id: 15,
            },
            '16': {
              top_conditions: [
                {
                  first_id: 29,
                  first_type: 'Answer',
                  first_node_id: 18,
                  operator: null,
                  second_id: null,
                  second_type: null,
                  second_node_id: null,
                },
              ],
              conditions: [],
              id: 16,
            },
          },
          managements: { '17': { top_conditions: [], conditions: [], id: 17 } },
          excluding_diagnosis: null,
        },
      },
    },
    '5': {
      id: 5,
      reference: 'DD5',
      label: 'Musculo-skeletal infection',
      differential: {
        top_conditions: [
          {
            first_id: 55,
            first_type: 'Answer',
            first_node_id: 31,
            operator: null,
            second_id: null,
            second_type: null,
            second_node_id: null,
          },
          {
            first_id: 57,
            first_type: 'Answer',
            first_node_id: 32,
            operator: null,
            second_id: null,
            second_type: null,
            second_node_id: null,
          },
        ],
        conditions: [],
      },
      nodes: {
        '1': { top_conditions: [], conditions: [], id: 1, children: [34] },
        '27': {
          top_conditions: [
            {
              first_id: 55,
              first_type: 'Answer',
              first_node_id: 31,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
            {
              first_id: 57,
              first_type: 'Answer',
              first_node_id: 32,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 27,
          children: [29],
        },
        '29': {
          top_conditions: [
            {
              first_id: 47,
              first_type: 'Answer',
              first_node_id: 27,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 29,
          children: [41, 19],
        },
        '31': {
          top_conditions: [
            {
              first_id: 59,
              first_type: 'Answer',
              first_node_id: 34,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 31,
          children: [27],
        },
        '32': {
          top_conditions: [
            {
              first_id: 59,
              first_type: 'Answer',
              first_node_id: 34,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 32,
          children: [27],
        },
        '34': {
          top_conditions: [
            {
              first_id: 6,
              first_type: 'Answer',
              first_node_id: 1,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 34,
          children: [31, 32],
        },
        '40': {
          top_conditions: [],
          conditions: [],
          id: 40,
          children: [15, 17],
        },
      },
      diagnosis: {
        '19': {
          top_conditions: [
            {
              first_id: 51,
              first_type: 'Answer',
              first_node_id: 29,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          disease_id: 5,
          name: 'Osteomyelitis / septic arthritis',
          id: 19,
          type: 'FinalDiagnostic',
          treatments: {
            '15': {
              top_conditions: [
                {
                  first_id: 71,
                  first_type: 'Answer',
                  first_node_id: 40,
                  operator: null,
                  second_id: null,
                  second_type: null,
                  second_node_id: null,
                },
              ],
              conditions: [],
              id: 15,
            },
            '33': { top_conditions: [], conditions: [], id: 33 },
            '42': { top_conditions: [], conditions: [], id: 42 },
          },
          managements: {
            '17': {
              top_conditions: [
                {
                  first_id: 71,
                  first_type: 'Answer',
                  first_node_id: 40,
                  operator: null,
                  second_id: null,
                  second_type: null,
                  second_node_id: null,
                },
              ],
              conditions: [],
              id: 17,
            },
          },
          excluding_diagnosis: null,
        },
        '41': {
          top_conditions: [
            {
              first_id: 50,
              first_type: 'Answer',
              first_node_id: 29,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          disease_id: 5,
          name: 'Test',
          id: 41,
          type: 'FinalDiagnostic',
          treatments: {},
          managements: {},
          excluding_diagnosis: null,
        },
      },
    },
  },
  nodes: {
    '1': {
      id: 1,
      type: 'Question',
      reference: 'E1',
      label: 'Age',
      description: null,
      priority: 'triage',
      category: 'Exposure',
      display_format: 'Input',
      value_format: 'Integer',
      qs: [{ id: 36, conditionValue: null }, { id: 37, conditionValue: null }],
      dd: [{ id: 5, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '3': {
          id: 3,
          reference: 'E1_1',
          label: 'less than 2 months',
          value: '2',
          operator: 'less',
        },
        '4': {
          id: 4,
          reference: 'E1_2',
          label: 'between 2 and 6 months',
          value: '2, 6',
          operator: 'between',
        },
        '5': {
          id: 5,
          reference: 'E1_3',
          label: 'between 6 and 12 months',
          value: '6, 12',
          operator: 'between',
        },
        '6': {
          id: 6,
          reference: 'E1_4',
          label: 'more than 12 months',
          value: '12',
          operator: 'more_or_equal',
        },
      },
    },
    '2': {
      id: 2,
      type: 'Question',
      reference: 'S3',
      label: 'Convulsions in current illness',
      description: null,
      priority: 'mandatory',
      category: 'Symptom',
      display_format: 'Input',
      value_format: 'Integer',
      qs: [{ id: 35, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '7': {
          id: 7,
          reference: 'S3_1',
          label: '2 or more',
          value: '2',
          operator: 'more_or_equal',
        },
        '8': {
          id: 8,
          reference: 'S3_2',
          label: 'less than 2',
          value: '2',
          operator: 'less',
        },
      },
    },
    '4': {
      id: 4,
      type: 'Question',
      reference: 'P6',
      label: 'What is MUAC size ?',
      description: null,
      priority: 'triage',
      category: 'Physical exam',
      display_format: 'Input',
      value_format: 'Float',
      qs: [{ id: 36, conditionValue: null }, { id: 37, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '9': {
          id: 9,
          reference: 'P6_1',
          label: 'less than 11.5',
          value: '11.5',
          operator: 'less',
        },
        '10': {
          id: 10,
          reference: 'P6_2',
          label: 'between 11.5 and 12.5',
          value: '11.5, 12.5',
          operator: 'between',
        },
        '11': {
          id: 11,
          reference: 'P6_3',
          label: '12.5 or more',
          value: '12.5',
          operator: 'more_or_equal',
        },
      },
    },
    '6': {
      top_conditions: [
        {
          first_id: 25,
          first_type: 'Answer',
          first_node_id: 12,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 22,
          first_type: 'Answer',
          first_node_id: 10,
          operator: 'and_operator',
          second_id: 23,
          second_type: 'Answer',
          second_node_id: 11,
        },
        {
          first_id: 19,
          first_type: 'Answer',
          first_node_id: 9,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      disease_id: 4,
      name: 'Severe lower respiratory tract infection',
      id: 6,
      type: 'FinalDiagnostic',
      treatments: {
        '14': {
          top_conditions: [
            {
              first_id: 29,
              first_type: 'Answer',
              first_node_id: 18,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 14,
        },
        '15': {
          top_conditions: [
            {
              first_id: 30,
              first_type: 'Answer',
              first_node_id: 18,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 15,
        },
        '16': {
          top_conditions: [
            {
              first_id: 29,
              first_type: 'Answer',
              first_node_id: 18,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 16,
        },
      },
      managements: { '17': { top_conditions: [], conditions: [], id: 17 } },
      excluding_diagnosis: null,
    },
    '7': {
      id: 7,
      type: 'Question',
      reference: 'S2',
      label: 'Cough',
      description: null,
      priority: 'mandatory',
      category: 'Symptom',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [],
      dd: [{ id: 4, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '15': {
          id: 15,
          reference: 'S2_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '16': {
          id: 16,
          reference: 'S2_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '8': {
      id: 8,
      type: 'Question',
      reference: 'S4',
      label: 'Drink as usual',
      description: null,
      priority: 'mandatory',
      category: 'Symptom',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [{ id: 18, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '17': {
          id: 17,
          reference: 'S4_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '18': {
          id: 18,
          reference: 'S4_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '9': {
      id: 9,
      type: 'Question',
      reference: 'P1',
      label: 'SAO2',
      description: null,
      priority: 'triage',
      category: 'Physical exam',
      display_format: 'Input',
      value_format: 'Integer',
      qs: [{ id: 35, conditionValue: null }],
      dd: [{ id: 4, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '19': {
          id: 19,
          reference: 'P1_1',
          label: '>/= 90%',
          value: '90',
          operator: 'more_or_equal',
        },
        '20': {
          id: 20,
          reference: 'P1_2',
          label: '< 90%',
          value: '90',
          operator: 'less',
        },
      },
    },
    '10': {
      id: 10,
      type: 'Question',
      reference: 'P3',
      label: 'Respiratory rate',
      description: null,
      priority: 'triage',
      category: 'Physical exam',
      display_format: 'Input',
      value_format: 'Integer',
      qs: [],
      dd: [{ id: 4, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '21': {
          id: 21,
          reference: 'P3_1',
          label: '< 97th%ile',
          value: '97',
          operator: 'less',
        },
        '22': {
          id: 22,
          reference: 'P3_2',
          label: '>/= 97th%ile',
          value: '97',
          operator: 'more_or_equal',
        },
      },
    },
    '11': {
      id: 11,
      type: 'Question',
      reference: 'P13',
      label: 'Lower chest indrawing',
      description: null,
      priority: 'basic',
      category: 'Physical exam',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [],
      dd: [{ id: 4, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '23': {
          id: 23,
          reference: 'P13_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '24': {
          id: 24,
          reference: 'P13_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '12': {
      id: 12,
      type: 'Question',
      reference: 'P14',
      label: 'Sever respiratory distress',
      description: null,
      priority: 'basic',
      category: 'Physical exam',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [],
      dd: [{ id: 4, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '25': {
          id: 25,
          reference: 'P14_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '26': {
          id: 26,
          reference: 'P14_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '13': {
      id: 13,
      type: 'Question',
      reference: 'P25',
      label: 'Tolerates PO liquid',
      description: null,
      priority: 'basic',
      category: 'Physical exam',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [{ id: 18, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '27': {
          id: 27,
          reference: 'P25_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '28': {
          id: 28,
          reference: 'P25_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '14': {
      id: 14,
      type: 'Treatment',
      reference: 'T1',
      label: 'Amoxicillin',
      description: null,
    },
    '15': {
      id: 15,
      type: 'Treatment',
      reference: 'T2',
      label: 'IM ceftriaxone',
      description: null,
    },
    '16': {
      id: 16,
      type: 'Treatment',
      reference: 'T9',
      label: 'Oral rehydration',
      description: null,
    },
    '17': {
      id: 17,
      type: 'Management',
      reference: 'M2',
      label: 'Refer',
      description: null,
    },
    '18': {
      top_conditions: [
        {
          first_id: 17,
          first_type: 'Answer',
          first_node_id: 8,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 27,
          first_type: 'Answer',
          first_node_id: 13,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      id: 18,
      reference: 'PS6',
      type: 'PredefinedSyndrome',
      nodes: {
        '8': { top_conditions: [], conditions: [], id: 8, children: [13, 18] },
        '13': {
          top_conditions: [
            {
              first_id: 18,
              first_type: 'Answer',
              first_node_id: 8,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 13,
          children: [18],
        },
      },
      answers: {
        '29': { id: 29, reference: 'PS6_1', label: 'Yes' },
        '30': { id: 30, reference: 'PS6_2', label: 'No' },
      },
      qs: [{ id: 40, conditionValue: null }],
      dd: [{ id: 4, conditionValue: null }],
      answer: null,
    },
    '19': {
      top_conditions: [
        {
          first_id: 51,
          first_type: 'Answer',
          first_node_id: 29,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      disease_id: 5,
      name: 'Osteomyelitis / septic arthritis',
      id: 19,
      type: 'FinalDiagnostic',
      treatments: {
        '15': {
          top_conditions: [
            {
              first_id: 71,
              first_type: 'Answer',
              first_node_id: 40,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 15,
        },
        '33': { top_conditions: [], conditions: [], id: 33 },
        '42': { top_conditions: [], conditions: [], id: 42 },
      },
      managements: {
        '17': {
          top_conditions: [
            {
              first_id: 71,
              first_type: 'Answer',
              first_node_id: 40,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 17,
        },
      },
      excluding_diagnosis: null,
    },
    '20': {
      id: 20,
      type: 'Question',
      reference: 'P7',
      label: 'Convulsing now',
      description: null,
      priority: 'triage',
      category: 'Physical exam',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [{ id: 35, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '31': {
          id: 31,
          reference: 'P7_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '32': {
          id: 32,
          reference: 'P7_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '21': {
      id: 21,
      type: 'Question',
      reference: 'P8',
      label: 'Lethargic or unconscious',
      description: null,
      priority: 'triage',
      category: 'Physical exam',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [{ id: 35, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '33': {
          id: 33,
          reference: 'P8_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '34': {
          id: 34,
          reference: 'P8_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '22': {
      id: 22,
      type: 'Question',
      reference: 'P2',
      label: 'Severe tachycardia (th %ile)',
      description: null,
      priority: 'triage',
      category: 'Physical exam',
      display_format: 'Input',
      value_format: 'Integer',
      qs: [{ id: 35, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '35': {
          id: 35,
          reference: 'P2_1',
          label: 'More than 90',
          value: '90',
          operator: 'more_or_equal',
        },
        '36': {
          id: 36,
          reference: 'P2_2',
          label: 'Less than 90',
          value: '90',
          operator: 'less',
        },
      },
    },
    '23': {
      id: 23,
      type: 'Question',
      reference: 'P9',
      label: 'Stiff neck',
      description: null,
      priority: 'mandatory',
      category: 'Physical exam',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [{ id: 35, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '37': {
          id: 37,
          reference: 'P9_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '38': {
          id: 38,
          reference: 'P9_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '24': {
      id: 24,
      type: 'Question',
      reference: 'S1',
      label: 'History of fever',
      description: null,
      priority: 'triage',
      category: 'Symptom',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [{ id: 34, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '39': {
          id: 39,
          reference: 'S1_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '40': {
          id: 40,
          reference: 'S1_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '25': {
      id: 25,
      type: 'Question',
      reference: 'P4',
      label: 'Axillary temperature',
      description: null,
      priority: 'triage',
      category: 'Physical exam',
      display_format: 'Input',
      value_format: 'Float',
      qs: [{ id: 34, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '41': {
          id: 41,
          reference: 'P4_1',
          label: 'More than 37.5',
          value: '37.5',
          operator: 'more_or_equal',
        },
        '42': {
          id: 42,
          reference: 'P4_2',
          label: 'Less than 37.5',
          value: '37.5',
          operator: 'less',
        },
      },
    },
    '26': {
      id: 26,
      type: 'Question',
      reference: 'P5',
      label: 'Weight for age (z-score)',
      description: null,
      priority: 'triage',
      category: 'Physical exam',
      display_format: 'Input',
      value_format: 'Float',
      qs: [{ id: 36, conditionValue: null }, { id: 37, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '43': {
          id: 43,
          reference: 'P5_1',
          label: 'less than -3',
          value: '-3',
          operator: 'less',
        },
        '44': {
          id: 44,
          reference: 'P5_2',
          label: 'Between -3 and -2',
          value: '-3,-2',
          operator: 'between',
        },
        '45': {
          id: 45,
          reference: 'P5_3',
          label: 'More than -2',
          value: '-2',
          operator: 'more_or_equal',
        },
      },
    },
    '27': {
      id: 27,
      type: 'Question',
      reference: 'A1',
      label: 'mRDT',
      description: null,
      priority: 'mandatory',
      category: 'Assessment/Test',
      display_format: 'DropDownList',
      value_format: 'Array',
      qs: [],
      dd: [{ id: 5, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '46': {
          id: 46,
          reference: 'A1_1',
          label: 'positive',
          value: null,
          operator: null,
        },
        '47': {
          id: 47,
          reference: 'A1_2',
          label: 'negative',
          value: null,
          operator: null,
        },
      },
    },
    '28': {
      id: 28,
      type: 'Question',
      reference: 'A2',
      label: 'SaO2 (%)',
      description: null,
      priority: 'mandatory',
      category: 'Assessment/Test',
      display_format: 'Input',
      value_format: 'Integer',
      qs: [{ id: 38, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '48': {
          id: 48,
          reference: 'A2_1',
          label: 'Less than 6',
          value: '6',
          operator: 'less',
        },
        '49': {
          id: 49,
          reference: 'A2_2',
          label: 'More than 6',
          value: '6',
          operator: 'more_or_equal',
        },
      },
    },
    '29': {
      id: 29,
      type: 'Question',
      reference: 'A3',
      label: 'CRP (mg/L)',
      description: null,
      priority: 'basic',
      category: 'Assessment/Test',
      display_format: 'Input',
      value_format: 'Float',
      qs: [],
      dd: [{ id: 5, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '50': {
          id: 50,
          reference: 'A3_1',
          label: 'Less than 20',
          value: '20',
          operator: 'less',
        },
        '51': {
          id: 51,
          reference: 'A3_2',
          label: 'Between 20 and 40',
          value: '20,40',
          operator: 'between',
        },
        '52': {
          id: 52,
          reference: 'A3_3',
          label: 'More than 40',
          value: '40',
          operator: 'more_or_equal',
        },
      },
    },
    '30': {
      id: 30,
      type: 'Question',
      reference: 'A4',
      label: 'SaO2 (%)',
      description: null,
      priority: 'basic',
      category: 'Assessment/Test',
      display_format: 'Input',
      value_format: 'Float',
      qs: [{ id: 39, conditionValue: null }],
      dd: [],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '53': {
          id: 53,
          reference: 'A4_1',
          label: 'Less than 3.3',
          value: '3.3',
          operator: 'less',
        },
        '54': {
          id: 54,
          reference: 'A4_2',
          label: 'More than 3.3',
          value: '3.3',
          operator: 'more_or_equal',
        },
      },
    },
    '31': {
      id: 31,
      type: 'Question',
      reference: 'S8',
      label: 'Extremity pain',
      description: null,
      priority: 'mandatory',
      category: 'Symptom',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [],
      dd: [{ id: 5, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '55': {
          id: 55,
          reference: 'S8_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '56': {
          id: 56,
          reference: 'S8_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '32': {
      id: 32,
      type: 'Question',
      reference: 'P24',
      label: 'Joint swelling',
      description: null,
      priority: 'mandatory',
      category: 'Physical exam',
      display_format: 'RadioButton',
      value_format: 'Boolean',
      qs: [],
      dd: [{ id: 5, conditionValue: null }],
      counter: 0,
      value: 0,
      answer: null,
      answers: {
        '57': {
          id: 57,
          reference: 'P24_1',
          label: 'Yes',
          value: null,
          operator: null,
        },
        '58': {
          id: 58,
          reference: 'P24_2',
          label: 'No',
          value: null,
          operator: null,
        },
      },
    },
    '33': {
      id: 33,
      type: 'Treatment',
      reference: 'T4',
      label: 'Cephalexin',
      description: null,
    },
    '34': {
      top_conditions: [
        {
          first_id: 39,
          first_type: 'Answer',
          first_node_id: 24,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 41,
          first_type: 'Answer',
          first_node_id: 25,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      id: 34,
      reference: 'PS1',
      type: 'PredefinedSyndrome',
      nodes: {
        '24': { top_conditions: [], conditions: [], id: 24, children: [34] },
        '25': { top_conditions: [], conditions: [], id: 25, children: [34] },
      },
      answers: {
        '59': { id: 59, reference: 'PS1_1', label: 'Yes' },
        '60': { id: 60, reference: 'PS1_2', label: 'No' },
      },
      qs: [],
      dd: [{ id: 5, conditionValue: null }],
      answer: null,
    },
    '35': {
      top_conditions: [
        {
          first_id: 7,
          first_type: 'Answer',
          first_node_id: 2,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 31,
          first_type: 'Answer',
          first_node_id: 20,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 33,
          first_type: 'Answer',
          first_node_id: 21,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 19,
          first_type: 'Answer',
          first_node_id: 9,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 35,
          first_type: 'Answer',
          first_node_id: 22,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 37,
          first_type: 'Answer',
          first_node_id: 23,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      id: 35,
      reference: 'PS2',
      type: 'PredefinedSyndrome',
      nodes: {
        '2': { top_conditions: [], conditions: [], id: 2, children: [35] },
        '9': { top_conditions: [], conditions: [], id: 9, children: [35] },
        '20': { top_conditions: [], conditions: [], id: 20, children: [35] },
        '21': { top_conditions: [], conditions: [], id: 21, children: [35] },
        '22': { top_conditions: [], conditions: [], id: 22, children: [35] },
        '23': { top_conditions: [], conditions: [], id: 23, children: [35] },
      },
      answers: {
        '61': { id: 61, reference: 'PS2_1', label: 'Yes' },
        '62': { id: 62, reference: 'PS2_2', label: 'No' },
      },
      qs: [{ id: 40, conditionValue: null }],
      dd: [],
      answer: null,
    },
    '36': {
      top_conditions: [
        {
          first_id: 43,
          first_type: 'Answer',
          first_node_id: 26,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 9,
          first_type: 'Answer',
          first_node_id: 4,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      id: 36,
      reference: 'DC1',
      type: 'PredefinedSyndrome',
      nodes: {
        '1': { top_conditions: [], conditions: [], id: 1, children: [4] },
        '4': {
          top_conditions: [
            {
              first_id: 5,
              first_type: 'Answer',
              first_node_id: 1,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 4,
          children: [36],
        },
        '26': { top_conditions: [], conditions: [], id: 26, children: [36] },
      },
      answers: {
        '63': { id: 63, reference: 'DC1_1', label: 'Yes' },
        '64': { id: 64, reference: 'DC1_2', label: 'No' },
      },
      qs: [{ id: 40, conditionValue: null }],
      dd: [],
      answer: null,
    },
    '37': {
      top_conditions: [
        {
          first_id: 44,
          first_type: 'Answer',
          first_node_id: 26,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 10,
          first_type: 'Answer',
          first_node_id: 4,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      id: 37,
      reference: 'DC2',
      type: 'PredefinedSyndrome',
      nodes: {
        '1': { top_conditions: [], conditions: [], id: 1, children: [4] },
        '4': {
          top_conditions: [
            {
              first_id: 5,
              first_type: 'Answer',
              first_node_id: 1,
              operator: null,
              second_id: null,
              second_type: null,
              second_node_id: null,
            },
          ],
          conditions: [],
          id: 4,
          children: [37],
        },
        '26': { top_conditions: [], conditions: [], id: 26, children: [37] },
      },
      answers: {
        '65': { id: 65, reference: 'DC2_1', label: 'Yes' },
        '66': { id: 66, reference: 'DC2_2', label: 'No' },
      },
      qs: [{ id: 40, conditionValue: null }],
      dd: [],
      answer: null,
    },
    '38': {
      top_conditions: [
        {
          first_id: 48,
          first_type: 'Answer',
          first_node_id: 28,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      id: 38,
      reference: 'DC3',
      type: 'PredefinedSyndrome',
      nodes: {
        '28': { top_conditions: [], conditions: [], id: 28, children: [38] },
      },
      answers: {
        '67': { id: 67, reference: 'DC3_1', label: 'Yes' },
        '68': { id: 68, reference: 'DC3_2', label: 'No' },
      },
      qs: [{ id: 40, conditionValue: null }],
      dd: [],
      answer: null,
    },
    '39': {
      top_conditions: [
        {
          first_id: 53,
          first_type: 'Answer',
          first_node_id: 30,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      id: 39,
      reference: 'DC4',
      type: 'PredefinedSyndrome',
      nodes: {
        '30': { top_conditions: [], conditions: [], id: 30, children: [39] },
      },
      answers: {
        '69': { id: 69, reference: 'DC4_1', label: 'Yes' },
        '70': { id: 70, reference: 'DC4_2', label: 'No' },
      },
      qs: [{ id: 40, conditionValue: null }],
      dd: [],
      answer: null,
    },
    '40': {
      top_conditions: [
        {
          first_id: 61,
          first_type: 'Answer',
          first_node_id: 35,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 30,
          first_type: 'Answer',
          first_node_id: 18,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 63,
          first_type: 'Answer',
          first_node_id: 36,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 65,
          first_type: 'Answer',
          first_node_id: 37,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 67,
          first_type: 'Answer',
          first_node_id: 38,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
        {
          first_id: 69,
          first_type: 'Answer',
          first_node_id: 39,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      id: 40,
      reference: 'C1',
      type: 'PredefinedSyndrome',
      nodes: {
        '18': { top_conditions: [], conditions: [], id: 18, children: [40] },
        '35': { top_conditions: [], conditions: [], id: 35, children: [40] },
        '36': { top_conditions: [], conditions: [], id: 36, children: [40] },
        '37': { top_conditions: [], conditions: [], id: 37, children: [40] },
        '38': { top_conditions: [], conditions: [], id: 38, children: [40] },
        '39': { top_conditions: [], conditions: [], id: 39, children: [40] },
      },
      answers: {
        '71': { id: 71, reference: 'C1_1', label: 'Yes' },
        '72': { id: 72, reference: 'C1_2', label: 'No' },
      },
      qs: [],
      dd: [{ id: 5, conditionValue: null }],
      answer: null,
    },
    '41': {
      top_conditions: [
        {
          first_id: 50,
          first_type: 'Answer',
          first_node_id: 29,
          operator: null,
          second_id: null,
          second_type: null,
          second_node_id: null,
        },
      ],
      conditions: [],
      disease_id: 5,
      name: 'Test',
      id: 41,
      type: 'FinalDiagnostic',
      treatments: {},
      managements: {},
      excluding_diagnosis: null,
    },
    '42': {
      id: 42,
      type: 'Treatment',
      reference: 'T12',
      label: 'TEST4',
      description: null,
    },
  },
  selected: true,
};
