export { default as Create } from './Create'
export { default as SetAnswer } from './SetAnswer'
export { default as Load } from './Load'
export { default as GetAll } from './GetAll'
export { default as UpdateDiagnosis } from './UpdateDiagnosis'
export { default as SaveMedicalCaseService } from './Save'
export { default as CloseMedicalCaseService } from './Close'
