export { default as Create } from './Create'
export { default as GetAll } from './GetAll'
export { default as Load } from './Load'
export { default as Insert } from './Insert'
export { default as UpdatePatientService } from './Update'
