# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'liwi_native' do
pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for liwi_native

  target 'liwi_native-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RNCViewpager', :path => '../node_modules/@react-native-community/viewpager'

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  end

  target 'liwi_nativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'liwi_native-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for liwi_native-tvOS


end


