# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'liwi_native' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for liwi_native

  target 'liwi_native-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  end

  target 'liwi_nativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'liwi_native-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for liwi_native-tvOS

  target 'liwi_native-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'

