import { StyleSheet } from 'react-native';
import { liwiColors } from '../../../../utils/constants';

export const styles = StyleSheet.create({
  label: {
    backgroundColor: liwiColors.redColor,
    color: liwiColors.whiteColor,
    fontSize: 20,
    padding: 4,
    borderRadius: 2,
    paddingLeft: 10,
    marginBottom: 10,
  },
  viewBox: { marginBottom: 20 },
  viewItem: { flex: 1, flexDirection: 'row', marginBottom: 5, backgroundColor: liwiColors.whiteColor, padding: 10 },
  flex50: { flex: 0.5 },
  box: {
    width: 150,
    borderRadius: 3,
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: liwiColors.whiteColor,
  },
  icon: { color: liwiColors.redColor, marginLeft: 5 },
  searchInputStyle: { color: '#CCC' },
  additionalText: {
    backgroundColor: liwiColors.redColor,
    color: liwiColors.whiteColor,
    padding: 4,
    borderRadius: 2,
    paddingLeft: 20,
    marginBottom: 20,
  },
  noRightMargin: { marginRight: 0 },
  noTopMargin: { marginTop: 0 },
  rowStyle: { marginTop: 10, marginBottom: 10 },
  container: {
    flexDirection: 'row',
  },
  iconInfo: { color: liwiColors.redColor },
  touchable: {
    marginRight: 7,
  },
  additionalDrugWrapper: { flexDirection: 'row', alignItems: 'center' },
  additionalDrugTitle: { flex: 1 },
  additionalDrugSubtitle: { flex: 1, textAlign: 'right' },
  additionalDrugName: {
    backgroundColor: 'white',
    marginBottom: 5,
    paddingHorizontal: 15,
    paddingVertical: 10,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  durationInput: {
    flex: 0.2,
    padding: 5,
    fontSize: 18,
    backgroundColor: liwiColors.lightGreyColor,
    marginBottom: 5,
    marginLeft: 5,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  warningBloc: {
    backgroundColor: liwiColors.orangeColor,
    borderRadius: 3,
    padding: 15,
    elevation: 1,
    marginLeft: 10,
    marginRight: 10,
    borderColor: liwiColors.lightGreyColor,
    marginBottom: 10,
    marginTop: 10,
  },
});
