export const actions = {
  MEDICAL_CASE_NEW: 'MEDICAL_CASE_NEW',
  MEDICAL_CASE_CLEAR: 'MEDICAL_CASE_CLEAR',
  MEDICAL_CASE_INITIATE: 'MEDICAL_CASE_INITIATE',
  MEDICAL_CASE_SET: 'MEDICAL_CASE_SET',
  INTERCEPT_ACTIONS: 'INTERCEPT_ACTIONS',
};
