import uuid from 'react-native-uuid';
import moment from 'moment';

export const patientTemplate = () => {
  const faker = require('faker');
  const patient = {
    id: uuid.v4(),
    uid: uuid.v4(),
    study_id: 'BigStudy',
    group_id: '5',
    medicalCases: [],
    fail_safe: false,
  };

  const medicalCase = {
    id: uuid.v4(),
    diagnostics: {
      '3': {
        id: 3,
        reference: 1,
        label: 'Dysentery',
        differential: { top_conditions: [], conditions: [] },
        instances: {
          '60': {
            top_conditions: [
              {
                first_id: 97,
                first_type: 'Answer',
                first_node_id: 61,
                operator: null,
                second_id: null,
                second_type: null,
                second_node_id: null,
                score: null,
              },
            ],
            conditions: [],
            id: 60,
            children: [59],
            final_diagnostic_id: null,
          },
          '61': {
            top_conditions: [
              {
                first_id: 98,
                first_type: 'Answer',
                first_node_id: 62,
                operator: null,
                second_id: null,
                second_type: null,
                second_node_id: null,
                score: null,
              },
            ],
            conditions: [],
            id: 61,
            children: [60],
            final_diagnostic_id: null,
          },
          '62': { top_conditions: [], conditions: [], id: 62, children: [61], final_diagnostic_id: null },
        },
        final_diagnostics: {
          '59': {
            top_conditions: [
              {
                first_id: 91,
                first_type: 'Answer',
                first_node_id: 60,
                operator: null,
                second_id: null,
                second_type: null,
                second_node_id: null,
                score: null,
              },
            ],
            conditions: [],
            diagnostic_id: 3,
            id: 59,
            label: 'Dysentery',
            type: 'FinalDiagnostic',
            drugs: {},
            managements: {},
            excluding_final_diagnostics: null,
            cc: 55,
          },
        },
      },
      '4': {
        id: 4,
        reference: 2,
        label: 'Dysmenorrhea',
        differential: { top_conditions: [], conditions: [] },
        instances: {
          '64': {
            top_conditions: [
              {
                first_id: 104,
                first_type: 'Answer',
                first_node_id: 66,
                operator: null,
                second_id: null,
                second_type: null,
                second_node_id: null,
                score: null,
              },
            ],
            conditions: [],
            id: 64,
            children: [63],
            final_diagnostic_id: null,
          },
          '65': {
            top_conditions: [
              {
                first_id: 104,
                first_type: 'Answer',
                first_node_id: 66,
                operator: null,
                second_id: null,
                second_type: null,
                second_node_id: null,
                score: null,
              },
            ],
            conditions: [],
            id: 65,
            children: [63],
            final_diagnostic_id: null,
          },
          '66': {
            top_conditions: [
              {
                first_id: 106,
                first_type: 'Answer',
                first_node_id: 67,
                operator: null,
                second_id: null,
                second_type: null,
                second_node_id: null,
                score: null,
              },
            ],
            conditions: [],
            id: 66,
            children: [64, 65],
            final_diagnostic_id: null,
          },
          '67': { top_conditions: [], conditions: [], id: 67, children: [66], final_diagnostic_id: null },
        },
        final_diagnostics: {
          '63': {
            top_conditions: [
              {
                first_id: 100,
                first_type: 'Answer',
                first_node_id: 64,
                operator: null,
                second_id: null,
                second_type: null,
                second_node_id: null,
                score: null,
              },
              {
                first_id: 102,
                first_type: 'Answer',
                first_node_id: 65,
                operator: null,
                second_id: null,
                second_type: null,
                second_node_id: null,
                score: null,
              },
            ],
            conditions: [],
            diagnostic_id: 4,
            id: 63,
            label: 'Dysmenorrhea',
            type: 'FinalDiagnostic',
            drugs: { '71': { top_conditions: [], conditions: [], id: 71, duration: null, description: '' } },
            managements: { '70': { top_conditions: [], conditions: [], id: 70, duration: null, description: '' } },
            excluding_final_diagnostics: null,
            cc: 53,
          },
        },
      },
    },
    nodes: {
      '37': {
        id: 37,
        type: 'Question',
        reference: 1,
        label: 'Birth date',
        description: null,
        is_mandatory: true,
        stage: 'registration',
        system: null,
        formula: null,
        category: 'basic_demographic',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Date',
        display_format: 'Date',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: faker.fake('{{date.past}}'),
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {},
      },
      '39': {
        id: 39,
        type: 'Question',
        reference: 1,
        label: 'Weight (kg)',
        description: null,
        is_mandatory: true,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'basic_measurement',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Float',
        display_format: 'Input',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {},
      },
      '40': {
        id: 40,
        type: 'Question',
        reference: 1,
        label: 'Heart rate',
        description: null,
        is_mandatory: false,
        stage: 'consultation',
        system: null,
        formula: null,
        category: 'vital_sign_anthropometric',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Float',
        display_format: 'Input',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {},
      },
      '41': {
        id: 41,
        type: 'Question',
        reference: 2,
        label: 'Respiratory rate',
        description: null,
        is_mandatory: false,
        stage: 'consultation',
        system: null,
        formula: null,
        category: 'vital_sign_anthropometric',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Float',
        display_format: 'Input',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {},
      },
      '42': {
        id: 42,
        type: 'Question',
        reference: 2,
        label: 'MUAC',
        description: 'Mid Upper Arm Circumference',
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'basic_measurement',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Float',
        display_format: 'Input',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {},
      },
      '48': {
        id: 48,
        type: 'Question',
        reference: 1,
        label: 'General',
        description: null,
        is_mandatory: true,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: 69,
        answers: {
          '69': { id: 69, reference: 1, label: 'Yes', value: null, operator: null },
          '70': { id: 70, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '49': {
        id: 49,
        type: 'Question',
        reference: 2,
        label: 'Skin and hair complaint ',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '71': { id: 71, reference: 1, label: 'Yes', value: null, operator: null },
          '72': { id: 72, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '50': {
        id: 50,
        type: 'Question',
        reference: 3,
        label: 'Eye complaint',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '73': { id: 73, reference: 1, label: 'Yes', value: null, operator: null },
          '74': { id: 74, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '51': {
        id: 51,
        type: 'Question',
        reference: 4,
        label: 'Ear/Nose/Mouth/Throat complaint',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '75': { id: 75, reference: 1, label: 'Yes', value: null, operator: null },
          '76': { id: 76, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '52': {
        id: 52,
        type: 'Question',
        reference: 5,
        label: 'Respiratory complaint',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '77': { id: 77, reference: 1, label: 'Yes', value: null, operator: null },
          '78': { id: 78, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '53': {
        id: 53,
        type: 'Question',
        reference: 6,
        label: 'Urine, genital and anal symptoms',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '79': { id: 79, reference: 1, label: 'Yes', value: null, operator: null },
          '80': { id: 80, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '54': {
        id: 54,
        type: 'Question',
        reference: 7,
        label: 'Neurological manifestations (Headache, convulsions or neck pain)',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '81': { id: 81, reference: 1, label: 'Yes', value: null, operator: null },
          '82': { id: 82, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '55': {
        id: 55,
        type: 'Question',
        reference: 8,
        label: 'Gastrointestinal symptoms',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '83': { id: 83, reference: 1, label: 'Yes', value: null, operator: null },
          '84': { id: 84, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '56': {
        id: 56,
        type: 'Question',
        reference: 9,
        label: 'Trauma, accidents, burns, pain, wounds',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '85': { id: 85, reference: 1, label: 'Yes', value: null, operator: null },
          '86': { id: 86, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '57': {
        id: 57,
        type: 'Question',
        reference: 10,
        label: 'Fever without obvious source',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '87': { id: 87, reference: 1, label: 'Yes', value: null, operator: null },
          '88': { id: 88, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '58': {
        id: 58,
        type: 'Question',
        reference: 11,
        label: 'Prevention and screening',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '89': { id: 89, reference: 1, label: 'Yes', value: null, operator: null },
          '90': { id: 90, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '59': {
        top_conditions: [
          {
            first_id: 91,
            first_type: 'Answer',
            first_node_id: 60,
            operator: null,
            second_id: null,
            second_type: null,
            second_node_id: null,
            score: null,
          },
        ],
        conditions: [],
        diagnostic_id: 3,
        id: 59,
        label: 'Dysentery',
        type: 'FinalDiagnostic',
        drugs: {},
        managements: {},
        excluding_final_diagnostics: null,
        cc: 55,
      },
      '60': {
        id: 60,
        type: 'Question',
        reference: 1,
        label: 'Blood in stool',
        description: null,
        is_mandatory: false,
        stage: 'consultation',
        system: 'digestive',
        formula: null,
        category: 'symptom',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [{ id: 3, conditionValue: false }],
        cc: [55],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '91': { id: 91, reference: 1, label: 'Yes', value: null, operator: null },
          '92': { id: 92, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '61': {
        id: 61,
        type: 'Question',
        reference: 2,
        label: 'Nb of loose or liquid stools over past 24 hours',
        description: null,
        is_mandatory: false,
        stage: 'consultation',
        system: 'digestive',
        formula: null,
        category: 'symptom',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Integer',
        display_format: 'Input',
        qs: [],
        dd: [{ id: 3, conditionValue: false }],
        cc: [55],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '93': { id: 93, reference: 1, label: '>=6', value: '6', operator: 'more_or_equal' },
          '94': { id: 94, reference: 2, label: '>=5', value: '5,6', operator: 'between' },
          '95': { id: 95, reference: 3, label: '>=4', value: '4,5', operator: 'between' },
          '96': { id: 96, reference: 4, label: '>=3', value: '3,4', operator: 'between' },
          '97': { id: 97, reference: 5, label: '<3', value: '3', operator: 'less' },
        },
      },
      '62': {
        id: 62,
        type: 'Question',
        reference: 3,
        label: 'Diarreha',
        description: null,
        is_mandatory: false,
        stage: 'consultation',
        system: 'digestive',
        formula: null,
        category: 'symptom',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [{ id: 3, conditionValue: true }],
        cc: [55],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '98': { id: 98, reference: 1, label: 'Yes', value: null, operator: null },
          '99': { id: 99, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '63': {
        top_conditions: [
          {
            first_id: 100,
            first_type: 'Answer',
            first_node_id: 64,
            operator: null,
            second_id: null,
            second_type: null,
            second_node_id: null,
            score: null,
          },
          {
            first_id: 102,
            first_type: 'Answer',
            first_node_id: 65,
            operator: null,
            second_id: null,
            second_type: null,
            second_node_id: null,
            score: null,
          },
        ],
        conditions: [],
        diagnostic_id: 4,
        id: 63,
        label: 'Dysmenorrhea',
        type: 'FinalDiagnostic',
        drugs: { '71': { top_conditions: [], conditions: [], id: 71, duration: null, description: '' } },
        managements: { '70': { top_conditions: [], conditions: [], id: 70, duration: null, description: '' } },
        excluding_final_diagnostics: null,
        cc: 53,
      },
      '64': {
        id: 64,
        type: 'Question',
        reference: 4,
        label: 'Very painful menstruation',
        description: null,
        is_mandatory: false,
        stage: 'consultation',
        system: 'urinary_reproductive',
        formula: null,
        category: 'symptom',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [{ id: 4, conditionValue: false }],
        cc: [53],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '100': { id: 100, reference: 1, label: 'Yes', value: null, operator: null },
          '101': { id: 101, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '65': {
        id: 65,
        type: 'Question',
        reference: 5,
        label: 'Abdominal pain',
        description: null,
        is_mandatory: false,
        stage: 'consultation',
        system: 'urinary_reproductive',
        formula: null,
        category: 'symptom',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [{ id: 4, conditionValue: false }],
        cc: [53],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '102': { id: 102, reference: 1, label: 'Yes', value: null, operator: null },
          '103': { id: 103, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '66': {
        id: 66,
        type: 'Question',
        reference: 6,
        label: 'Menstruating now',
        description: null,
        is_mandatory: false,
        stage: 'consultation',
        system: 'urinary_reproductive',
        formula: null,
        category: 'symptom',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [{ id: 4, conditionValue: false }],
        cc: [53],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '104': { id: 104, reference: 1, label: 'Yes', value: null, operator: null },
          '105': { id: 105, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '67': {
        id: 67,
        type: 'Question',
        reference: 7,
        label: 'Menarche (history of menstruation)',
        description: null,
        is_mandatory: false,
        stage: 'consultation',
        system: 'urinary_reproductive',
        formula: null,
        category: 'symptom',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [{ id: 4, conditionValue: true }],
        cc: [53],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '106': { id: 106, reference: 1, label: 'Yes', value: null, operator: null },
          '107': { id: 107, reference: 3, label: 'No', value: null, operator: null },
        },
      },
      '70': {
        id: 70,
        type: 'HealthCare',
        category: 'management',
        reference: 1,
        label: 'Stay at home ',
        description: null,
      },
      '71': {
        id: 71,
        type: 'HealthCare',
        category: 'drug',
        reference: 1,
        label: 'Dopamine',
        description: null,
        weight_question_id: 39,
        formulations: [
          {
            medication_form: 'tablet',
            administration_route_category: 'Enteral',
            administration_route_name: 'Orally',
            liquid_concentration: null,
            dose_form: 200,
            unique_dose: null,
            by_age: false,
            breakable: 2,
            minimal_dose_per_kg: 80,
            maximal_dose_per_kg: 100,
            maximal_dose: 3000,
            doses_per_day: 3,
          },
          {
            medication_form: 'suspension',
            administration_route_category: 'Parenteral injectable',
            administration_route_name: 'IV',
            liquid_concentration: 5,
            dose_form: 5,
            unique_dose: null,
            by_age: false,
            breakable: null,
            minimal_dose_per_kg: 80,
            maximal_dose_per_kg: 100,
            maximal_dose: 300,
            doses_per_day: 1,
          },
        ],
      },
      '74': {
        id: 74,
        type: 'Question',
        reference: 2,
        label: 'First name',
        description: null,
        is_mandatory: true,
        stage: 'registration',
        system: null,
        formula: null,
        category: 'basic_demographic',
        is_triage: false,
        is_identifiable: true,
        value_format: 'String',
        display_format: 'String',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: faker.fake('{{name.firstName}}'),
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {},
      },
      '75': {
        id: 75,
        type: 'Question',
        reference: 3,
        label: 'Last name',
        description: null,
        is_mandatory: true,
        stage: 'registration',
        system: null,
        formula: null,
        category: 'basic_demographic',
        is_triage: false,
        is_identifiable: true,
        value_format: 'String',
        display_format: 'String',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: faker.fake('{{name.lastName}}'),
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {},
      },
      '76': {
        id: 76,
        type: 'Question',
        reference: 12,
        label: 'Fever complaint',
        description: null,
        is_mandatory: false,
        stage: 'triage',
        system: null,
        formula: null,
        category: 'complaint_category',
        is_triage: false,
        is_identifiable: false,
        value_format: 'Boolean',
        display_format: 'RadioButton',
        qs: [],
        dd: [],
        cc: [],
        conditioned_by_cc: [],
        referenced_in: [],
        counter: 0,
        value: null,
        reference_table_x_id: null,
        reference_table_y_id: null,
        reference_table_male: null,
        reference_table_female: null,
        cc_general: true,
        answer: null,
        answers: {
          '108': { id: 108, reference: 1, label: 'Yes', value: null, operator: null },
          '109': { id: 109, reference: 3, label: 'No', value: null, operator: null },
        },
      },
    },
    triage: { conditions: { '37': [{ complaint_category_id: 97, answer_id: 144 }] } },
    synchronized_at: null,
    updated_at: faker.fake('{{date.past}}'),
    created_at: faker.fake('{{date.past}}'),
    status: 'in_creation',
    patient_id: 'string',
    fail_safe: false,
    version_id: 3,
    metaData: {
      consultation: {
        medicalHistory: [39, 42, 60, 61, 62, 64, 65, 66, 67],
        physicalExam: [],
      },
      diagnosticsStrategy: {
        managementQuestions: [],
      },
      patientupsert: {
        custom: [37, 74, 75],
      },
      tests: {
        tests: [],
      },
      triage: {
        basicMeasurements: [39, 42],
        complaintCategories: [49, 50, 51, 48, 52, 53, 54, 55, 56, 57, 58, 76],
        firstLookAssessments: [],
      },
    },
    mobile_config: {
      left_top_question_id: 37,
      first_top_right_question_id: 74,
      second_top_right_question_id: 75,
      questions_orders: {
        basic_measurement: [39, 42],
        consultation_related: [],
        complaint_category: [49, 50, 51, 48, 52, 53, 54, 55, 56, 57, 58, 76],
        basic_demographic: [74, 75, 37],
        demographic: [],
        unique_triage_physical_sign: [],
        unique_triage_question: [],
      },
    },
    activities: [
      {
        id: uuid.v4(),
        stage: 'creation',
        clinician: 'Alain Fresco',
        nodes: '[]',
        mode: 'client-server',
        mac_address: faker.fake('{{internet.mac}}'),
        created_at: moment().toDate(),
        synchronized_at: moment().toDate(),
        fail_safe: false,
      },
    ],
  };
  medicalCase.json = JSON.stringify(medicalCase);
  medicalCase.patient_id = patient.id;
  patient.medicalCases.push(medicalCase);
  return patient;
};
